### PR TITLE
Add TIP-4 Non-Fungible Token 

### PR DESCRIPTION
**Pull request by nftalliance**

### CODE REVIEW

**Review by ilyar — CHANGES_REQUESTED** [review]
1. link to reder docks
2. reference implementation
3. optional gas consumption graphs, an example is here https://t.me/EverscaleGuild/117
4. it would be great to make a rebase https://github.com/everscale-org/docs/blob/main/CONTRIBUTING.md

**Comment by ilyar** [comment]
I hope that it will be possible to independently find a consensus, at least in the name, through dialogue with the current working groups
https://github.com/everscale-org/docs/pull/15 and https://github.com/everscale-org/docs/pull/20

**Comment by nftalliance** [comment]
> link to reder docks
https://docs.nftalliance.org/standard/TIP-4

> reference implementation
https://docs.nftalliance.org/standard/TIP-4#implementation

https://github.com/itgoldio/everscale-tip
https://github.com/itgoldio/everscale-tip-samples

>optional gas consumption graphs, an example is here https://t.me/EverscaleGuild/117
gas computation it is part of implementation of standard. It can be different for different implementation.

It's not a part of standard


> it would be great to make a rebase https://github.com/everscale-org/docs/blob/main/CONTRIBUTING.md

Another PR https://github.com/everscale-org/docs/pull/66

**Comment by nftalliance** [comment]
> I hope that it will be possible to independently find a consensus, at least in the name, through dialogue with the current working groups #15 and #20

#15 closed

**Comment by ilyar** [comment]
https://github.com/everscale-org/docs/pull/66

**Pull request closed without merging**
