### PR TITLE
Extend TIP 4.2 with `metaverse.region` JSON model

### PR DESCRIPTION
**Pull request by vp-mazekine**
Add a new JSON model to the standard: `metaverse.region` - for tokenized areas in metaverses.

### CODE REVIEW

**Comment by itgoldio** [comment]
@vp-mazekine 

Hi, can you describe integration scenario for other applications?

For example:

Can I sell this NFT on marketplace? How to show it in marketplace?
Can i show it in wallet? How to show it?

**Comment by vp-mazekine** [comment]
Thanks for your questions.

> Can I sell this NFT on marketplace? 

Yes, definitely. It is one of the main reasons for tokenization: beyond the control of your land (private access, privileges, etc.), it will allow anyone the easy transfer of property through the marketplace.

> How to show it in marketplace?

As I see it, each game should have a tailored marketplace that shows the visual map inside the metaverse. It can be flat, 3D, or isometric. On such a map, based on the shape of the tokenized region, you can visually see the piece of land/space you are acquiring. Example of such maps: [Minecraft](https://minecraftonline.com/map/#/0/64/0/max/Freedonia%20-%20overworld/Day). [GTA](https://gta-5-map.com/), [Sandbox](https://www.sandbox.game/en/map/) etc.

> Can i show it in wallet? How to show it?

It can be shown as a generic NFT plate in the wallet. However, the URL specified in the `meta.server.url` object may allow the wallet to extract some preview metadata (like server icon and name) to enrich the plate.

It will, however, require the compatibility with popular games that may be solved through some kind of oracle.

**Comment by itgoldio** [comment]
@vp-mazekine 

Can we add more metadata about product to NFT json or we can get it from collection contract? 

> Address where the server is located. Typically, the URL, from which the server actual metadata like name, description, etc. can be extracted

why we don't store name, description inside NFT?

```{
	"type": "metaverse.region",
        "metaverse_url":"https://minecraft.everscale.network",
        "name":"Minecraft",
        "description":"First everscale minecraft",
	"meta": {
		"server": {
			"type": "minecraft",
			"url": "http://10.10.10.10:25565",
			"pubkey": "c843d424bba89625d64fb592975180023e46b499388856fa832e287484adc4aa"
		},
		"signature": "cc9d3377f78d33a3d2d412d173f2b6e9e6dd06af19749d95032ea7c78eb07d873ddfe0b241a190900422732207dbbdc987b1bbcfd74d56404f0ab0d65d4f930e"
	},
	"regions": [
		{
			"shape": "cuboid",
			"params": {
				"position1": {
					"x": "0",
					"y": "-50",
					"z": "0"
				},
				"position2": {
					"x": "16",
					"y": "200",
					"z": "16"
				}
			}
		}
	]
}
```

**Comment by vp-mazekine** [comment]
> I think we are trying to provide for specific cases in the TIP-4.2 standard, this task seems to be impossible

In general, I agree with you. However, there are not too many use cases now, and I see no problem to keep a few of them in the standard text for now.

> I think it will be logical to solve more the base (for example https://nomicon.io/Standards/Tokens/NonFungibleToken/Metadata#interface) case and the case of extending the possible cases in a more formal way for this is the specification JSON Schema (https://json-schema.org/specification.html)

`TokenMetadata` is a good example; as soon as we agree on its structure, I will be happy to update schemas as well. However, not all fields from Near example are applicable for all kinds of NFTs. 

I would make the metadata object and all its elements optional, as a rule, to ensure maximum compatibility.

As for JSON schemas, I don't understand how that will help at the moment.

**Review by ilyar — CHANGES_REQUESTED** [review]
it is necessary to fix the comments to the commits, please follow the convention https://github.com/everscale-org/docs/blob/main/CONTRIBUTING.md#main-flow

**Comment by vp-mazekine** [comment]
> it is necessary to fix the comments to the commits, please follow the convention https://github.com/everscale-org/docs/blob/main/CONTRIBUTING.md#main-flow

Github allows doing this only for the latest commit. It was fixed accordingly.

**Pull request merged**
