### PR TITLE
Set TIP4.2 as Final

### PR DESCRIPTION
**Pull request by rualekseev**
Set TIP4.2 as Final

### CODE REVIEW

**Comment by rualekseev** [comment]
Hello,

I'm team member of [grandbazar ](https://grandbazar.io/)and [itgold](https://itgold.io/) teams

I support this PR

**Comment by VSemenchuk** [comment]
I support this pr

**Comment by ini0n** [comment]
I'm team member of numiz
I support this PR

**Comment by aleksandr-hramcov** [comment]
I support this pr

**Comment by kokkekpek** [comment]
I support this PR

**Comment by itgoldio** [comment]
@ilyar Can you merge this PR

**Comment by ilyar** [comment]
To support the proposed option, it is necessary to implement one of the possible cases using NFT and present it in this discussion with your comments.

**Review by ilyar — CHANGES_REQUESTED** [review]
To support the proposed option, it is necessary to implement one of the possible cases using NFT and present it in this discussion with your comments.

**Comment by ilyar** [comment]
https://hackmd.io/JLC8gtOITRajh0TCT_486Q — feedback is collected in this document

**Pull request closed without merging**
