### PR TITLE
TIP4.1 set Final state

### PR DESCRIPTION
**Pull request by rualekseev**
Set TIP4.1 as Final

### CODE REVIEW

**Comment by rualekseev** [comment]
Hello,

I'm team member of [grandbazar ](https://grandbazar.io) and [itgold](https://itgold.io) teams

I support this PR

**Comment by VSemenchuk** [comment]
I support this pr

**Comment by ini0n** [comment]
I'm team member of numiz
I support this PR

**Comment by aleksandr-hramcov** [comment]
I support this pr

**Comment by kokkekpek** [comment]
I support this PR after some updates only. I think that we made a good standard, but new changes appeared in the process of implementation

## 1. Need to change callback format
You need to do this wherever callbacks are used

**Now**
```solidity
struct CallbackParams {
    uint128 value;      // ever value will be sent to address
    TvmCell payload;    // custom payload will be proxied to address
}
```

```solidity
mapping(address => CallbackParams) callbacks
```

**Must be**
```solidity
struct CallbackParams {
	address receiver;   // Callback receiver address
    uint128 value;      // Ever value will be sent to receiver address
    TvmCell payload;    // Custom payload will be proxied to receiver address
}
```

```
CallbackParams[] callbacks
```

### Почему лучше использовать массив, а не map?
It's **cheaper to loop over an array than it is over a map**. It is silly to pass a callback to the map that you will not call - you need loop over all the callbacks

**Now**
```solidity
for ((address destination, CallbackParams parameters) : callbacks) {
    INFTTransfer(destination).onNftTransfer {
        value: parameters.value,
        flag: MessageFlags.SENDER_PAYS_FEES,
        bounce: false
    }(_id, oldOwner, newOwner, oldManager, newOwner, _collection, sendGasTo, parameters.payload);
}
```

**Must be**
```solidity
for (uint i; i < callbacks.length; ++i) {
	CallbackParams callback = callbacks[i];
    INFTTransfer(callback.receiver).onNftTransfer {
        value: callback.value,
        flag: MessageFlags.SENDER_PAYS_FEES,
        bounce: false
    }(_id, oldOwner, newOwner, oldManager, newOwner, _collection, sendGasTo, callback.payload);
}
```

## 2. Move the CallbackParams structure from all interfaces, and transfer it to the Callback.sol library
This is necessary to **remove code duplication**, as well as to **avoid compilation conflicts**

**Now**
```
import "Callback.sol";

interface TIP4_1NFT {

    struct CallbackParams {
        uint128 value;      // ever value will be sent to address
        TvmCell payload;    // custom payload will be proxied to address
    }

    // ...

    /// @notice Change NFT owner
    /// @dev Invoked from manager address only
    /// @dev Emit OwnerChanged
    /// @param newOwner New owner of NFT
    /// @param sendGasTo Address to send remaining gas
    /// @param callbacks Callbacks array to send by addresses. It can be empty
    function changeOwner(address newOwner, address sendGasTo, mapping(address => CallbackParams) callbacks) external;

    // ...

}
```


**Must be**
Callback.sol
```solidity
pragma ton-solidity >= 0.58.0;

library Callback {
    struct Params {
	    address receiver;   // Callback receiver address
        uint128 value;      // Ever value will be sent to receiver address
        TvmCell payload;    // Custom payload will be proxied to receiver address
    }
}
```

```solidity
import "Callback.sol";

interface TIP4_1NFT {

    // ...

    /// @notice Change NFT owner
    /// @dev Invoked from manager address only
    /// @dev Emit OwnerChanged
    /// @param newOwner New owner of NFT
    /// @param sendGasTo Address to send remaining gas
    /// @param callbacks Callbacks array to send by addresses. It can be empty
    function changeOwner(address newOwner, address sendGasTo, Callback.Params[] callbacks) external;

    // ...

}
```

After that, I agree to finalize

**Comment by kokkekpek** [comment]
Also, after the finalization, I consider it important to remake the illustrations in the standard into a more popular format. Now the format is not editable. We made illustrations in [miro](https://miro.com/app). It was a mistake. Miro does not allow you to export the source file in a vector format. [@Ilyar](https://github.com/ilyar) suggests using `plantuml`. In my opinion, this is a visually bad solution, although it is convenient for people working with text. It is much better to make a good vector and save it in one of the formats that anyone familiar with graphic editors: EPS, SVG or AI

**Comment by ilyar** [comment]
To support the proposed option, it is necessary to implement one of the possible cases using NFT and present it in this discussion with your comments.

**Review by ilyar — CHANGES_REQUESTED** [review]
To support the proposed option, it is necessary to implement one of the possible cases using NFT and present it in this discussion with your comments.

**Comment by ilyar** [comment]
https://hackmd.io/JLC8gtOITRajh0TCT_486Q — feedback is collected in this document

**Pull request closed without merging**
