### PR TITLE
update rework

### PR DESCRIPTION
**Pull request by ilyar**
- [x] **depends:** #325
- [x] **preview:** https://everscale-org.github.io/preview/PR-328/
- [ ] because there is a big change in the structure, you need to add a redirect of old links to new ones

### CODE REVIEW

**Comment by ilyar** [comment]
updated preview: https://everscale-org.github.io/preview/PR-328/

**Review by elasticLove1 — APPROVED** [review]

**Comment by qwadratic** [comment]
nice update. lets merge it

**Review by qwadratic — APPROVED** [review]

**Comment by qwadratic** [comment]
yet a nice one. lets release.

**Review by qwadratic — APPROVED** [review]

**Comment by qwadratic** [comment]
ок

**Review by cryshado — APPROVED** [review]

**Review by qwadratic — APPROVED** [review]

**Review by qwadratic — APPROVED** [review]

**Comment by ilyar** [comment]
**🚀 updated preview:** https://everscale-org.github.io/preview/PR-328/

**Review by a-zorina — APPROVED** [review]

**Review by qwadratic — APPROVED** [review]

**Review by qwadratic — APPROVED** [review]

**Review by ch1seL — APPROVED** [review]

**Pull request merged**
