### PR TITLE
 Add TIP-4 Non-Fungible Token

### PR DESCRIPTION
**Pull request by nftalliance**
## (Status:Review) Non-Fungible Token TIP-4.1
General information about NFT collection and NFT tokens.

## (Status:Review) Non-Fungible Token JSON Metadata TIP-4.2
General information about NFT metadata

## (Status:Review) On-chain indexes TIP-4.3
On-chain Indexes solves easy and fast searching any data in blockchain. 

## (Status:Draft) On-chain storage TIP-4.4
Using the Storage contract, you can store NFT-related bytes in blockchain.

### CODE REVIEW

**Comment by nftalliance** [comment]
@ilyar 
> link to reder docks

https://docs.nftalliance.org/standard/TIP-4

> reference implementation

https://docs.nftalliance.org/standard/TIP-4#implementation
https://github.com/itgoldio/everscale-tip
https://github.com/itgoldio/everscale-tip-samples

>optional gas consumption graphs, an example is here https://t.me/EverscaleGuild/117

gas computation it is part of implementation of standard. It can be different for different implementation.
It's not a part of standard

> it would be great to make a rebase https://github.com/everscale-org/docs/blob/main/CONTRIBUTING.md
make it

**Comment by ilyar** [comment]
> > it would be great to make a rebase https://github.com/everscale-org/docs/blob/main/CONTRIBUTING.md
>
> make it

@nftalliance  done, take this thread for yourself and continue it https://github.com/everscale-org/docs/tree/add-TIP-4

**Comment by ilyar** [comment]
> https://github.com/everscale-org/docs/tree/add-TIP-4

@kokkekpek updated

**Comment by nftalliance** [comment]
@nftalliance destination branch changed to [everscale-org:add-TIP-4](https://github.com/everscale-org/docs/tree/add-TIP-4)

**Comment by ilyar** [comment]
@nftalliance  for example how to use  `https://github.com/everscale-org/docs/tree/add-TIP-4` https://github.com/everscale-org/docs/pull/85

**Pull request closed without merging**
