### PR TITLE
Added TIP-4.X liquid-nft standard

### PR DESCRIPTION
**Pull request by SolderingArmor**
Liquid NFT format offers the most flexible solutions to any built-in mechanics without the need of any additional changes from wallets or marketplaces.

### CODE REVIEW

**Review by ilyar — CHANGES_REQUESTED** [review]
The description provided is too short and does not contain a description of the interfaces, while links to external resources (https://github.com/SolderingArmor/liquid-nft/blob/master/STANDARD.md) have a more complete description. It is necessary to make a more complete description along with the interfaces.

**Comment by ivankote** [comment]
@SolderingArmor the idea of master/print objects is very nice

However, in my opinion the base standard should only describe the approach to create single objects , object collections and ownership transfer

What do you think?

**Comment by SolderingArmor** [comment]
> What do you think?

@ivankote, in my opinion base/extended standard complicated development, usage and integration of the standard for both end users and developers. It may look nice and have great structure on paper but I try to focus on real-world usage.

**Comment by ilyar** [comment]
I hope that it will be possible to independently find a consensus, at least in the name, through dialogue with the current working groups
https://github.com/everscale-org/docs/pull/15 and https://github.com/everscale-org/docs/pull/20

**Pull request closed without merging**
