### PR TITLE
feature/add-tvm-opcodes-list

### PR DESCRIPTION
**Pull request by MrSufferer**
### What is this PR?

Origin: https://github.com/everscale-org/bounties/issues/32
This PR contains a workflow code pipeline for the list of all TVM opcodes.

### Changes

Including: 
- A folder at src/arch/ that contains markdown generation logic, also can be rendered at the docs website
- CSV file: contain the aggregated information from instructions.csv, tvm.tex(or initial TVM paper), and Everscale Extended Instructions, with an additional column that represented tvm_assembler.
- GitHub workflow file that auto writes the .md after there are push changes to the CSV

### Progress

The opcodes collecting job is done. Also fixed the missing description of some opcodes.

Problems:
- Still haven't tested the gas calculation of some new opcodes. 
- Still haven't figured out the tvm_asm of some complex opcodes. We may need to discuss this more.

Question?
- What is the layout visual of the expanded column I should handle? I've implemented a single column

### CODE REVIEW

**Comment by ilyar** [comment]
@everscale-org/docs 
:rocket: **preview** https://everscale-org.github.io/preview/PR-342/arch/opcodes/tvm_instructions

**Review by ilyar — CHANGES_REQUESTED** [review]
The current result looks very unfinished, especially when compared to the current reference outcome (https://github.com/ton-blockchain/docs/tree/master/docs/smart-contracts/tvm-instructions). The expected result should be no worse than the reference and should take into account the specific features of Everscale, which involve the division of the current virtual machine opcodes into at least two main categories: core opcodes used in the main network and additional opcodes for the specialized Gosh network. Additionally, considering an alternative to Python in favor of a similar npm package should be explored.

**Comment by ilyar** [comment]
:rocket: **update preview** https://everscale-org.github.io/preview/PR-342/arch/opcodes/tvm_instructions

**Comment by qwadratic** [comment]
IMO it lacks general rules of how the gas is calculated

Here is the reference from original specification by Telegram: https://ton.org/tvm.pdf
Appendix A, section 1:

image

**Comment by gadillacer** [comment]
@ilyar seems like I misunderstood something from the beginning.

@qwadratic
- Are the empty lines you said from the gas and tvm_asm columns?
- The data from the expanded column is just an example. What do you think I should put into it?

Will try to update more. Thanks!

**Comment by gadillacer** [comment]
@ilyar I've updated a bit according to your requests. Check pls.

Hope you can provide me next step to do after that.

**Comment by ilyar** [comment]
@gadillacer it’s hard for me to tell you exactly what needs to be changed this process is creative at the moment the result turned out worse than the existing reference, you yourself can see it on the final render, thanks for trying to do it

**Review by ilyar — CHANGES_REQUESTED** [review]
it’s hard for me to tell you exactly what needs to be changed this process is creative at the moment the result turned out worse than the existing reference, you yourself can see it on the final render, thanks for trying to do it

**Pull request closed without merging**
