### PR TITLE
standard: add TIP-3.2

### PR DESCRIPTION
**Pull request by ilyar**

### CODE REVIEW

**Comment by azhogin** [comment]
Hi, it is incompatible with the current EverX implementation, because EverX wallet have pubkey even for internal-ownership mode (to support many wallets for one owner). So, for EverX wallet credentials are `{pubkey, owner}`.
Are you sure you don't want to support many wallets for one owner (with default pubkey=0)?
Like `walletOf(address owner, uint256 pubkey = 0)`.

**Comment by ilyar** [comment]
@vp-mazekine @pavlovdog Please complete this document

**Comment by pavlovdog** [comment]
@ilyar done, check it out.

**Comment by ilyar** [comment]
@pavlovdog check and approve if ok

**Review by pavlovdog — APPROVED** [review]
SGTM

**Review by Futurizt — CHANGES_REQUESTED** [review]
Could you please address this comment
https://github.com/everscale-org/docs/pull/44#issuecomment-1152128296

**Comment by pavlovdog** [comment]
@Futurizt this PR describes the specific sub-type of TIP3, where the token wallets are owned by other contracts (eg wallets), not by the public keys. Describe EverX standard in a separate TIP3.X.

**Comment by ilyar** [comment]
> @azhogin @Futurizt this PR describes the specific sub-type of TIP3, where the token wallets are owned by other contracts (eg wallets), not by the public keys. Describe EverX standard in a separate TIP3.X.

image
@Futurizt There is a grain of meaning in these words, and I think that's how we want to do it. Is this the current plan for the implementation of standards?

**Review by eternalflow — APPROVED** [review]

**Pull request merged**
